import type { Campaign, User } from './types';
import { PlaceHolderImages } from './placeholder-images';

export const campaigns: Campaign[] = [
  {
    id: 101,
    name: 'Summer Sale Meta Ads',
    platform: 'Meta',
    budget: 2000,
    impressions: 120000,
    clicks: 4800,
    conversions: 350,
    revenue: 7600,
    status: 'Active',
    roi: 280,
  },
  {
    id: 102,
    name: 'Q4 Google Search',
    platform: 'Google Ads',
    budget: 5000,
    impressions: 350000,
    clicks: 7000,
    conversions: 420,
    revenue: 12500,
    status: 'Active',
    roi: 150,
  },
  {
    id: 103,
    name: 'LinkedIn B2B Leads',
    platform: 'LinkedIn',
    budget: 3500,
    impressions: 80000,
    clicks: 1200,
    conversions: 80,
    revenue: 9500,
    status: 'Paused',
    roi: 171,
  },
  {
    id: 104,
    name: 'Spring Collection Twitter',
    platform: 'Twitter',
    budget: 1500,
    impressions: 95000,
    clicks: 3500,
    conversions: 210,
    revenue: 3200,
    status: 'Ended',
    roi: 113,
  },
  {
    id: 105,
    name: 'Holiday Promo Google Ads',
    platform: 'Google Ads',
    budget: 7500,
    impressions: 550000,
    clicks: 11000,
    conversions: 700,
    revenue: 25000,
    status: 'Active',
    roi: 233,
  },
  {
    id: 106,
    name: 'New Product Launch Meta',
    platform: 'Meta',
    budget: 4000,
    impressions: 250000,
    clicks: 8000,
    conversions: 500,
    revenue: 15000,
    status: 'Active',
    roi: 275,
  },
];

export const users: User[] = [
  {
    id: 1,
    name: 'Admin User',
    email: 'admin@adsparkx.com',
    role: 'Admin',
    avatar: PlaceHolderImages.find((img) => img.id === 'user-avatar-1')?.imageUrl || '',
  },
  {
    id: 2,
    name: 'Analyst Jane',
    email: 'jane.doe@adsparkx.com',
    role: 'Analyst',
    avatar: PlaceHolderImages.find((img) => img.id === 'user-avatar-2')?.imageUrl || '',
  },
  {
    id: 3,
    name: 'Viewer John',
    email: 'john.smith@adsparkx.com',
    role: 'Viewer',
    avatar: PlaceHolderImages.find((img) => img.id === 'user-avatar-3')?.imageUrl || '',
  },
  {
    id: 4,
    name: 'Sarah Lee',
    email: 'sarah.lee@adsparkx.com',
    role: 'Analyst',
    avatar: PlaceHolderImages.find((img) => img.id === 'user-avatar-4')?.imageUrl || '',
  },
];

export const ctrData = [
  { date: 'Jan', ctr: 2.5 },
  { date: 'Feb', ctr: 2.8 },
  { date: 'Mar', ctr: 2.6 },
  { date: 'Apr', ctr: 3.1 },
  { date: 'May', ctr: 3.5 },
  { date: 'Jun', ctr: 3.2 },
  { date: 'Jul', ctr: 3.8 },
  { date: 'Aug', ctr: 3.6 },
  { date: 'Sep', ctr: 4.1 },
  { date: 'Oct', ctr: 4.5 },
  { date: 'Nov', ctr: 4.2 },
  { date: 'Dec', ctr: 4.8 },
];

export const revenueData = [
  { date: 'Jan', revenue: 12300 },
  { date: 'Feb', revenue: 18900 },
  { date: 'Mar', revenue: 22500 },
  { date: 'Apr', revenue: 23100 },
  { date: 'May', revenue: 34200 },
  { date: 'Jun', revenue: 25500 },
  { date: 'Jul', revenue: 34800 },
  { date: 'Aug', revenue: 29800 },
  { date: 'Sep', revenue: 41200 },
  { date: 'Oct', revenue: 45500 },
  { date: 'Nov', revenue: 51200 },
  { date: 'Dec', revenue: 64800 },
];
